version: "3.8"

services:
  papermc:
    image: itzg/minecraft-server
    container_name: papermc
    restart: always
    networks:
      - dokploy-network
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - MEMORY=4G
      - TYPE=paper
      - PAPER_VERSION=latest
    volumes:
      - ./:/data  # Mount the entire repository root directory to /data

volumes:
  minecraft-data:
    driver: local

networks:
  dokploy-network:
    external: true
