version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    restart: always
    environment:
      EULA: "TRUE"  # Automatically accept the Minecraft EULA
      TYPE: "PAPER"  # Specify the server type as PaperMC
    ports:
      - "25565:25565"  # Minecraft server port
    volumes:
      - minecraft-data:/data 

volumes:
  minecraft-data:
    driver: local

networks:
  default:
    external:
      name: dokploy-network 
